package example;

import com.soklet.HttpServer;
import com.soklet.McpRateLimiter;
import com.soklet.McpServer;
import com.soklet.Soklet;
import com.soklet.SokletConfig;
import com.soklet.SokletStartupException;
import com.soklet.SseServer;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;
import java.util.Set;

/** Executes consumer-generated routing through real listeners using only public API. */
public final class ConsumerSmoke {
  public static void main(String[] args) throws Exception {
    if (args.length != 0) {
      require(args.length == 1, "Expected one negative-control name");
      expectDiscoveryFailure(args[0]);
      return;
    }
    ClassLoader loader = ConsumerSmoke.class.getClassLoader();
    require(loader.getResource("META-INF/soklet/resource-method-lookup-table") != null,
        "Missing consumer HTTP/SSE route index: configure SokletProcessor");
    require(loader.getResource("META-INF/soklet/mcp-endpoint-descriptor-providers") != null,
        "Missing consumer MCP descriptor index: configure SokletProcessor");
    int httpPort = freePort();
    int mcpPort;
    do { mcpPort = freePort(); } while (mcpPort == httpPort);
    int ssePort;
    do { ssePort = freePort(); } while (ssePort == httpPort || ssePort == mcpPort);
    McpServer mcp = McpServer.withPort(mcpPort).host("127.0.0.1")
        .allowedHosts(Set.of("127.0.0.1"))
        .toolRateLimiter(McpRateLimiter.fromInMemoryDefaults()).build();
    SokletConfig.Builder builder = SokletConfig.withHttpServer(
        HttpServer.withPort(httpPort).host("127.0.0.1").build()).mcpServer(mcp);
    boolean supportsSse = Runtime.version().feature() >= 21;
    // Do not install a reflective resolver: these requests must use the packaged
    // lookup table generated by SokletProcessor. The driver includes SSE source
    // in the compiled fixture only when its consumer runtime supports live SSE.
    if (supportsSse)
      builder.sseServer(SseServer.withPort(ssePort).host("127.0.0.1").build());
    try (Soklet soklet = Soklet.fromConfig(builder.build())) {
      soklet.start();
      HttpClient client = HttpClient.newBuilder().version(HttpClient.Version.HTTP_1_1)
          .connectTimeout(Duration.ofSeconds(5)).build();
      HttpResponse<String> hello = client.send(HttpRequest.newBuilder(
          URI.create("http://127.0.0.1:" + httpPort + "/hello"))
          .timeout(Duration.ofSeconds(5)).GET().build(), HttpResponse.BodyHandlers.ofString());
      require(hello.statusCode() == 200 && hello.body().equals("consumer-ok"),
          "Generated HTTP route failed: " + hello.statusCode() + " " + hello.body());
      get(client, httpPort, "/stream", "packaged-stream");
      get(client, httpPort, "/source", "packaged-source");
      post(client, mcpPort, "server/discover", null, "", "2026-07-28");
      post(client, mcpPort, "tools/call", "catalog.search",
          "\"name\":\"catalog.search\",\"arguments\":{\"query\":\"sprocket\"},",
          "Match for sprocket");
      post(client, mcpPort, "prompts/get", "catalog.prompt",
          "\"name\":\"catalog.prompt\",\"arguments\":{\"query\":\"prompt\"},", "prompt!");
      if (supportsSse) {
        HttpResponse<java.io.InputStream> stream = client.send(HttpRequest.newBuilder(
            URI.create("http://127.0.0.1:" + ssePort + "/events"))
            .timeout(Duration.ofSeconds(5)).header("Accept", "text/event-stream").GET().build(),
            HttpResponse.BodyHandlers.ofInputStream());
        try (var body = stream.body()) {
          require(stream.statusCode() == 200, "Generated SSE route failed: " + stream.statusCode());
          CompletableFuture<Void> delivery = CompletableFuture.runAsync(() -> {
            try {
              BufferedReader input = new BufferedReader(new InputStreamReader(body, StandardCharsets.UTF_8));
              String line;
              do {
                line = input.readLine();
                require(line != null, "SSE ended before its initialization event");
              } while (line.isEmpty() || line.startsWith(":"));
              require(line.equals("data: packaged-sse") && "".equals(input.readLine()),
                  "SSE event payload or framing changed");
            } catch (java.io.IOException failure) {
              throw new RuntimeException(failure);
            }
          });
          delivery.get(5, TimeUnit.SECONDS);
          require(ConsumerOwnership.initialized.await(5, TimeUnit.SECONDS), "SSE initializer did not finish setup");
          require(soklet.shutdown().toCompletableFuture().get(10, TimeUnit.SECONDS).isComplete(),
              "Packaged SSE shutdown left residual activity");
        }
      }
    }
    require(ConsumerOwnership.sourceCloses.get() == 1 && ConsumerOwnership.inputCloses.get() == 1,
        "Packaged HTTP resource/source cleanup was not exactly once");
    System.out.println("Consumer HTTP/MCP" + (supportsSse ? "/SSE" : "")
        + " packaged routing passed on Java " + Runtime.version().feature());
  }

  private static void expectDiscoveryFailure(String control) throws Exception {
    boolean noProcessor = control.equals("no-processor");
    boolean missingIndex = control.equals("missing-http-index");
    boolean corruptIndex = control.equals("corrupt-http-index");
    require(noProcessor || missingIndex || corruptIndex, "Unknown negative control: " + control);
    if (!noProcessor)
      require(ConsumerSmoke.class.getClassLoader().getResource(
          "META-INF/soklet/mcp-endpoint-descriptor-providers") != null,
          "Negative control must preserve the MCP descriptor index");

    int httpPort = freePort();
    int mcpPort;
    do { mcpPort = freePort(); } while (mcpPort == httpPort);
    int ssePort;
    do { ssePort = freePort(); } while (ssePort == httpPort || ssePort == mcpPort);
    SokletConfig.Builder builder = SokletConfig.withHttpServer(
        HttpServer.withPort(httpPort).host("127.0.0.1").build());
    if (!noProcessor)
      builder.mcpServer(McpServer.withPort(mcpPort).host("127.0.0.1")
          .allowedHosts(Set.of("127.0.0.1"))
          .toolRateLimiter(McpRateLimiter.fromInMemoryDefaults()).build());
    if (Runtime.version().feature() >= 21)
      builder.sseServer(SseServer.withPort(ssePort).host("127.0.0.1").build());

    SokletStartupException failure = null;
    // Deliberately bypass the HTTP resource-presence guard in main(). Only a
    // failure from real default resolver/framework startup satisfies this test.
    try (Soklet soklet = Soklet.fromConfig(builder.build())) {
      try {
        soklet.start();
      } catch (SokletStartupException expected) {
        failure = expected;
      }
    }
    require(failure != null, control + " unexpectedly started successfully");
    String expectedMessage = corruptIndex
        ? "Unable to process Soklet's Resource Method lookup table."
        : "No Soklet Resource Methods were found.";
    Throwable cause = failure.getCause();
    require(cause != null && cause.getMessage() != null
        && cause.getMessage().startsWith(expectedMessage),
        control + " failed for an unrelated reason: " + failure);
    require(corruptIndex ? cause instanceof RuntimeException : cause instanceof IllegalStateException,
        control + " did not report the expected framework discovery failure type");
    assertPortFree(httpPort);
    assertPortFree(mcpPort);
    assertPortFree(ssePort);
    System.out.println("PASS\t" + control + "\tFRAMEWORK_DISCOVERY_FAILURE");
  }

  private static void assertPortFree(int port) throws Exception {
    try (ServerSocket socket = new ServerSocket(port, 0, InetAddress.getByName("127.0.0.1"))) {
      require(socket.isBound(), "Port could not be rebound after failed startup: " + port);
    }
  }

  private static void get(HttpClient client, int port, String path, String expected) throws Exception {
    HttpResponse<String> response = client.send(HttpRequest.newBuilder(
        URI.create("http://127.0.0.1:" + port + path)).timeout(Duration.ofSeconds(5)).GET().build(),
        HttpResponse.BodyHandlers.ofString());
    require(response.statusCode() == 200 && response.body().equals(expected),
        "Generated streaming route failed: " + path + " " + response.statusCode() + " " + response.body());
  }

  private static void post(HttpClient client, int port, String method, String name,
      String fields, String expected) throws Exception {
    String body = "{\"jsonrpc\":\"2.0\",\"id\":2,\"method\":\"" + method
        + "\",\"params\":{" + fields + "\"_meta\":{"
        + "\"io.modelcontextprotocol/protocolVersion\":\"2026-07-28\","
        + "\"io.modelcontextprotocol/clientCapabilities\":{}}}}";
    HttpRequest.Builder request = HttpRequest.newBuilder(
        URI.create("http://127.0.0.1:" + port + "/catalog/mcp"))
        .timeout(Duration.ofSeconds(5)).header("Content-Type", "application/json")
        .header("Accept", "application/json, text/event-stream")
        .header("MCP-Protocol-Version", "2026-07-28").header("Mcp-Method", method);
    if (name != null)
      request.header("Mcp-Name", name);
    HttpResponse<String> result = client.send(request.POST(HttpRequest.BodyPublishers.ofString(body)).build(),
        HttpResponse.BodyHandlers.ofString());
    require(result.statusCode() == 200 && !result.body().contains("\"error\":")
        && result.body().contains(expected), method + " failed: " + result.statusCode() + " " + result.body());
  }

  private static int freePort() throws Exception {
    try (ServerSocket socket = new ServerSocket(0, 0, InetAddress.getByName("127.0.0.1"))) {
      return socket.getLocalPort();
    }
  }

  private static void require(boolean condition, String message) {
    if (!condition)
      throw new AssertionError(message);
  }
}
